feat: [CI-12641]: Add OIDC support for Hosted VM
drone-plugins/drone-gcs pull request #74
Opened 2024-05-16 17:00 UTC by abhay084

Added the changes for OIDC support authentication in drone-gcs plugin. 

We will use the OIDC identity provider for GCP to generate the federal token, which will be used to create the OIDC access token. Then OIDC will be used by authenticate with gcp having the same permission as service account.

https://github.com/drone-plugins/drone-gcs/assets/59717751/3f84bdf3-f10f-4b4c-b0ec-75ed302bd75a

2024-05-28 06:48 UTC, Sapa96 approved these changes

2024-05-29 09:27 UTC, raghavharness requested changes

2024-05-29 09:27 UTC, raghavharness commented on main.go
> +
remove extra line

2024-05-29 09:27 UTC, raghavharness commented on main.go
> +		logrus.Fatalf("Error getting Google Cloud Access Token: %s", err)
return err

2024-06-03 05:46 UTC, raghavharness approved these changes

2024-06-03 11:34 UTC, merged